# Generated by Django 5.2.5 on 2025-08-18 06:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("currency", models.CharField(default="CLP", max_length=3)),
                (
                    "currency_to_USD",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activa"),
                            ("FROZEN", "Congelada"),
                            ("CLOSED", "Cerrada"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "per_tx_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2000000.00"), max_digits=18
                    ),
                ),
                (
                    "daily_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("500000.00"), max_digits=18
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("channel", models.CharField(default="APP", max_length=30)),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="nucleo.account",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["owner"], name="nucleo_acco_owner_i_0bd38d_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["number"], name="nucleo_acco_number_7fa598_idx"),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(
                fields=["account", "created_at"], name="nucleo_with_account_e1293f_idx"
            ),
        ),
    ]
