# Generated by Django 5.2.5 on 2025-08-18 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0002_alter_withdrawal_request_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("owner", "number"), name="unique_account_number"
            ),
        ),
    ]
