# Generated by Django 5.2.5 on 2025-08-18 22:05

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0004_alter_account_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="unique_account_number",
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="nucleo_acco_owner_i_0bd38d_idx",
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="nucleo_acco_number_7fa598_idx",
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("number"),
                name="unique_account_number",
            ),
        ),
    ]
