# Generated by Django 5.2.5 on 2025-08-21 01:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0005_remove_account_unique_account_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("channel", models.CharField(default="APP", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="nucleo.account",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account", "created_at"],
                        name="nucleo_depo_account_56834f_idx",
                    )
                ],
            },
        ),
    ]
